apiVersion: v1
kind: Secret
metadata:
  name: docker-user-pass
  annotations:
    tekton.dev/docker-0: https://index.docker.io # Described below
type: kubernetes.io/basic-auth
stringData:
  username: oscarfarg
  password: 95945549-0f5b-4206-a164-f35b71f34685
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
  namespace: tekton-pipelines
secrets:
  - name: docker-user-pass
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: builder
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods","configmaps","secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete","view"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete","view"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: build-robot-role-binding
subjects:
- kind: ServiceAccount
  name: build-robot
  namespace: demos
roleRef:
  kind: ClusterRole 
  name: builder
  apiGroup: rbac.authorization.k8s.io
